name: CI/CD

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
            node-version: 18


      - name: Install dependencies
        run: yarn


      - name: Test mode DEV
        run: npm run dev  
        
        

